export { default as bigCoinTracker } from "../img/big-Cointracker.png";
export { default as bigGlass } from "../img/big-Glass.png";
export { default as bigLastfmClone } from "../img/big-LastfmClone.png";
export { default as bigMyWebReact } from "../img/big-my-web-react.png";
export { default as bigNetflixClone } from "../img/big-NetflixClone.png";
export { default as bigPTPO } from "../img/big-PTPO.png";
export { default as bigTwiiterClone } from "../img/big-twitterCloneCoding.png";
export { default as bigMyWebReactV2 } from "../img/big-my-web-react-v2.png";
export { default as bigMatitsogo } from "../img/big-Matitsogo.png";
